export const SITE_CONFIG = {
  eventName: "NEXUS 2026",
  collegeName: "Vanguard Institute of Technology",
  collaboration: "IIT Delhi",
  tagline: "10 CLUBS. ONE UNIVERSE.",
  eventDate: new Date("2026-10-21T09:00:00+05:30"),
  venue: "Vanguard Institute of Technology, New Delhi",
  contactEmail: "nexus2026@vanguardit.edu",
  socialLinks: {
    instagram: "https://instagram.com/nexus2026",
    linkedin: "https://linkedin.com/company/nexus2026",
    youtube: "https://youtube.com/@nexus2026",
  },
} as const;

export interface EventItem {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  categoryIcon: string;
  clubId?: string;
  teamSize: string;
  duration: string;
  venue: string;
  date: string;
  time: string;
  fee: string;
  description: string;
  rules: string[];
  prizes: { position: string; amount: string }[];
  image: string;
}

export interface ClubItem {
  id: string;
  name: string;
  code: string;
  tagline: string;
  description: string;
  accentColor: string;
  bgGradient: string;
  category: string;
  leadName: string;
  leadRole: string;
  memberCount: number;
  activityIds: string[];
  image: string;
}

export const EVENT_CATEGORIES = [
  {
    id: "tech",
    title: "TECH HEROES",
    icon: "⚡",
    color: "#3b82f6",
    description: "Code. Build. Innovate.",
  },
  {
    id: "battle",
    title: "BATTLE ARENA",
    icon: "⚔️",
    color: "#e11d48",
    description: "Compete. Conquer. Dominate.",
  },
  {
    id: "intelligence",
    title: "INTELLIGENCE DIVISION",
    icon: "🧠",
    color: "#8b5cf6",
    description: "Think. Solve. Decode.",
  },
  {
    id: "creative",
    title: "CREATIVE UNIVERSE",
    icon: "🎨",
    color: "#f59e0b",
    description: "Imagine. Create. Inspire.",
  },
] as const;

export const CLUBS: ClubItem[] = [
  {
    id: "cyber-forge",
    name: "CYBER FORGE CLUB",
    code: "CLUB // 01",
    tagline: "Systems, Algorithms & Heavy Computation",
    description: "The primary engineering collective at NEXUS. Pushing modern algorithms, high-frequency computing, and systems design to absolute breaking point.",
    accentColor: "#3b82f6",
    bgGradient: "from-blue-950/40 via-slate-950 to-[#050508]",
    category: "Technical",
    leadName: "Dr. Vikram Patel",
    leadRole: "Chief Technical Strategist",
    memberCount: 340,
    activityIds: ["arc-reactor", "pixel-forge"],
    image: "/events/coding.jpg",
  },
  {
    id: "web-craft",
    name: "WEB CRAFT GUILD",
    code: "CLUB // 02",
    tagline: "Next-Gen Web Architecture & Distributed Interfaces",
    description: "Architects of the modern web. Specialized in micro-frontends, realtime websocket mesh networks, and high-performance WebGL interfaces.",
    accentColor: "#06b6d4",
    bgGradient: "from-cyan-950/40 via-slate-950 to-[#050508]",
    category: "Development",
    leadName: "Ananya Desai",
    leadRole: "Guild Master",
    memberCount: 280,
    activityIds: ["web-wars"],
    image: "/events/webdev.jpg",
  },
  {
    id: "ai-syndicate",
    name: "AI SYNDICATE",
    code: "CLUB // 03",
    tagline: "Neural Networks, LLMs & Autonomous Agents",
    description: "Exploring artificial general intelligence, multi-modal neural models, and real-time computer vision pipelines for real-world deployment.",
    accentColor: "#8b5cf6",
    bgGradient: "from-purple-950/40 via-slate-950 to-[#050508]",
    category: "Artificial Intelligence",
    leadName: "Rahul Krishnan",
    leadRole: "AI Research Lead",
    memberCount: 420,
    activityIds: ["neural-nexus"],
    image: "/events/aiml.jpg",
  },
  {
    id: "esports-arena",
    name: "ESPORTS ARENA",
    code: "CLUB // 04",
    tagline: "Tactical Combat, Reflex Engineering & Competitive Gaming",
    description: "The high-octane gaming division of NEXUS. Hosting official tactical 5v5 tournaments, battle royales, and reflex-based competition.",
    accentColor: "#e11d48",
    bgGradient: "from-rose-950/40 via-slate-950 to-[#050508]",
    category: "Gaming",
    leadName: "Karan Verma",
    leadRole: "Arena Commander",
    memberCount: 650,
    activityIds: ["cyber-clash", "quest-royale"],
    image: "/events/esports.jpg",
  },
  {
    id: "debate-league",
    name: "ORATORY & DEBATE LEAGUE",
    code: "CLUB // 05",
    tagline: "Geopolitics, Tech Ethics & Strategic Argumentation",
    description: "Where sharp rhetoric meets analytical rigor. Debating technological sovereignty, AI ethics, and planetary policy under high-stakes parliamentary rules.",
    accentColor: "#f59e0b",
    bgGradient: "from-amber-950/40 via-slate-950 to-[#050508]",
    category: "Literary & Strategy",
    leadName: "Meera Nair",
    leadRole: "League Moderator",
    memberCount: 190,
    activityIds: ["war-of-words"],
    image: "/events/debate.jpg",
  },
  {
    id: "intel-corps",
    name: "INTELLIGENCE CORPS",
    code: "CLUB // 06",
    tagline: "Rapid-Fire Knowledge, Trivia & Cross-Domain Intel",
    description: "The sharpest technical trivia division. Testing knowledge across quantum mechanics, computer architecture, space exploration, and sci-fi history.",
    accentColor: "#10b981",
    bgGradient: "from-emerald-950/40 via-slate-950 to-[#050508]",
    category: "Quizzing",
    leadName: "Arjun Mehta",
    leadRole: "Intel Director",
    memberCount: 220,
    activityIds: ["mind-matrix"],
    image: "/events/quiz.jpg",
  },
  {
    id: "cipher-labs",
    name: "CIPHER & PUZZLE LABS",
    code: "CLUB // 07",
    tagline: "Cryptology, Steganography & Logical Enigmas",
    description: "Deciphering multi-layered cryptograms, steganographic files, and labyrinthine puzzles designed by cryptography specialists.",
    accentColor: "#ec4899",
    bgGradient: "from-pink-950/40 via-slate-950 to-[#050508]",
    category: "Cryptology",
    leadName: "Siddharth Rao",
    leadRole: "Chief Cryptographer",
    memberCount: 175,
    activityIds: ["enigma"],
    image: "/events/puzzle.jpg",
  },
  {
    id: "design-matrix",
    name: "DESIGN MATRIX CLUB",
    code: "CLUB // 08",
    tagline: "UI/UX Architecture, Spatial Design & Product Design",
    description: "Defining futuristic human-computer interaction, spatial user interfaces, and sleek product design systems.",
    accentColor: "#6366f1",
    bgGradient: "from-indigo-950/40 via-slate-950 to-[#050508]",
    category: "Design",
    leadName: "Priya Sharma",
    leadRole: "Design Director",
    memberCount: 310,
    activityIds: ["vision-craft"],
    image: "/events/design.jpg",
  },
  {
    id: "cinema-reels",
    name: "CINEMA & REELS CLUB",
    code: "CLUB // 09",
    tagline: "Cinematography, Storyboarding & Visual Storytelling",
    description: "Capturing cinematic narratives, high-energy trailers, and visual storytelling in short-form and documentary media.",
    accentColor: "#d97706",
    bgGradient: "from-yellow-950/40 via-slate-950 to-[#050508]",
    category: "Media & Film",
    leadName: "Rohan Kapoor",
    leadRole: "Creative Director",
    memberCount: 260,
    activityIds: ["reel-rush"],
    image: "/events/reel.jpg",
  },
  {
    id: "lens-shutter",
    name: "LENS & SHUTTER CLUB",
    code: "CLUB // 10",
    tagline: "Street, Macro & High-Speed Event Photography",
    description: "Freezing motion in real-time. Documenting every peak moment, light trail, and emotional victory across the NEXUS arena.",
    accentColor: "#14b8a6",
    bgGradient: "from-teal-950/40 via-slate-950 to-[#050508]",
    category: "Photography",
    leadName: "Neha Gupta",
    leadRole: "Lead Photographer",
    memberCount: 290,
    activityIds: ["shutter-strike"],
    image: "/events/photography.jpg",
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "arc-reactor",
    title: "ARC REACTOR",
    subtitle: "Coding Challenge",
    category: "tech",
    categoryIcon: "⚡",
    clubId: "cyber-forge",
    teamSize: "2–4",
    duration: "3 Hours",
    venue: "Computer Lab 01",
    date: "21 October 2026",
    time: "10:00 AM – 1:00 PM",
    fee: "Free Entry",
    description: "A high-intensity coding battle where teams solve algorithmic challenges under pressure. Channel your inner genius and build solutions that push boundaries.",
    rules: [
      "Teams of 2-4 members",
      "Languages: C++, Java, Python, JavaScript",
      "Internet access restricted during competition",
      "Plagiarism leads to disqualification",
      "Judge's decision is final",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹25,000" },
      { position: "🥈 2nd Place", amount: "₹15,000" },
      { position: "🥉 3rd Place", amount: "₹10,000" },
    ],
    image: "/events/coding.jpg",
  },
  {
    id: "web-wars",
    title: "WEB WARS",
    subtitle: "Web Development",
    category: "tech",
    categoryIcon: "⚡",
    clubId: "web-craft",
    teamSize: "1–3",
    duration: "4 Hours",
    venue: "Computer Lab 02",
    date: "21 October 2026",
    time: "10:00 AM – 2:00 PM",
    fee: "Free Entry",
    description: "Design and develop a complete website from scratch. From responsive layouts to dynamic features — show us what you can build.",
    rules: [
      "Teams of 1-3 members",
      "Any frontend/backend tech stack allowed",
      "Pre-built templates not allowed",
      "Project must be built from scratch during the event",
      "Judging based on design, functionality, and creativity",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹20,000" },
      { position: "🥈 2nd Place", amount: "₹12,000" },
      { position: "🥉 3rd Place", amount: "₹8,000" },
    ],
    image: "/events/webdev.jpg",
  },
  {
    id: "neural-nexus",
    title: "NEURAL NEXUS",
    subtitle: "AI/ML Challenge",
    category: "tech",
    categoryIcon: "⚡",
    clubId: "ai-syndicate",
    teamSize: "2–3",
    duration: "5 Hours",
    venue: "AI Lab",
    date: "21 October 2026",
    time: "9:00 AM – 2:00 PM",
    fee: "Free Entry",
    description: "Build an AI/ML model to solve a real-world problem. From data preprocessing to model deployment — prove your machine learning mastery.",
    rules: [
      "Teams of 2-3 members",
      "Dataset provided at the start",
      "Pre-trained models allowed with citation",
      "Submissions must include code and documentation",
      "Evaluation on accuracy, innovation, and presentation",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹30,000" },
      { position: "🥈 2nd Place", amount: "₹18,000" },
      { position: "🥉 3rd Place", amount: "₹10,000" },
    ],
    image: "/events/aiml.jpg",
  },
  {
    id: "pixel-forge",
    title: "PIXEL FORGE",
    subtitle: "Hackathon",
    category: "tech",
    categoryIcon: "⚡",
    clubId: "cyber-forge",
    teamSize: "3–5",
    duration: "24 Hours",
    venue: "Main Auditorium",
    date: "21 October 2026",
    time: "9:00 AM (24h)",
    fee: "Free Entry",
    description: "The ultimate 24-hour hackathon. Build a product, pitch it, win it. From ideation to prototype — this is where legends are made.",
    rules: [
      "Teams of 3-5 members",
      "Theme revealed at start",
      "Working prototype required",
      "Pitch presentation of 5 minutes",
      "Use of APIs and open-source libraries allowed",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹50,000" },
      { position: "🥈 2nd Place", amount: "₹30,000" },
      { position: "🥉 3rd Place", amount: "₹15,000" },
    ],
    image: "/events/hackathon.jpg",
  },
  {
    id: "cyber-clash",
    title: "CYBER CLASH",
    subtitle: "Esports Tournament",
    category: "battle",
    categoryIcon: "⚔️",
    clubId: "esports-arena",
    teamSize: "5",
    duration: "6 Hours",
    venue: "Gaming Arena",
    date: "21 October 2026",
    time: "11:00 AM – 5:00 PM",
    fee: "Free Entry",
    description: "5v5 esports showdown. Strategize, communicate, and outplay your opponents in the ultimate gaming battle.",
    rules: [
      "Teams of 5 players",
      "Game: Valorant",
      "Best of 3 format (Finals: Best of 5)",
      "Players must bring their own peripherals",
      "Anti-cheat monitoring active",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹35,000" },
      { position: "🥈 2nd Place", amount: "₹20,000" },
      { position: "🥉 3rd Place", amount: "₹10,000" },
    ],
    image: "/events/esports.jpg",
  },
  {
    id: "war-of-words",
    title: "WAR OF WORDS",
    subtitle: "Debate Championship",
    category: "battle",
    categoryIcon: "⚔️",
    clubId: "debate-league",
    teamSize: "2",
    duration: "3 Hours",
    venue: "Seminar Hall",
    date: "21 October 2026",
    time: "2:00 PM – 5:00 PM",
    fee: "Free Entry",
    description: "Words are your weapons. Argue, persuade, and dominate in this high-stakes debate championship.",
    rules: [
      "Teams of 2 debaters",
      "Topics given 30 minutes before round",
      "Each speaker gets 5 minutes",
      "Rebuttal time: 2 minutes per team",
      "Parliamentary debate format",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹15,000" },
      { position: "🥈 2nd Place", amount: "₹8,000" },
      { position: "🥉 3rd Place", amount: "₹5,000" },
    ],
    image: "/events/debate.jpg",
  },
  {
    id: "mind-matrix",
    title: "MIND MATRIX",
    subtitle: "Technical Quiz",
    category: "intelligence",
    categoryIcon: "🧠",
    clubId: "intel-corps",
    teamSize: "2–3",
    duration: "2 Hours",
    venue: "Lecture Hall 3",
    date: "21 October 2026",
    time: "10:00 AM – 12:00 PM",
    fee: "Free Entry",
    description: "Test your technical knowledge across CS, electronics, science, and mathematics in this rapid-fire quiz challenge.",
    rules: [
      "Teams of 2-3 members",
      "3 rounds: MCQ, Rapid Fire, Buzzer",
      "No electronic devices",
      "Negative marking in Round 1",
      "Tie-breaker: fastest correct answer",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹12,000" },
      { position: "🥈 2nd Place", amount: "₹7,000" },
      { position: "🥉 3rd Place", amount: "₹4,000" },
    ],
    image: "/events/quiz.jpg",
  },
  {
    id: "enigma",
    title: "ENIGMA",
    subtitle: "Puzzle Challenge",
    category: "intelligence",
    categoryIcon: "🧠",
    clubId: "cipher-labs",
    teamSize: "1–2",
    duration: "1.5 Hours",
    venue: "Room 105",
    date: "21 October 2026",
    time: "3:00 PM – 4:30 PM",
    fee: "Free Entry",
    description: "Crack codes, solve riddles, and decode encrypted messages. The ultimate puzzle-solving challenge for the sharpest minds.",
    rules: [
      "Individual or pairs",
      "5 levels of increasing difficulty",
      "No internet or external tools",
      "Time-based scoring",
      "Hints available with penalty",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹8,000" },
      { position: "🥈 2nd Place", amount: "₹5,000" },
      { position: "🥉 3rd Place", amount: "₹3,000" },
    ],
    image: "/events/puzzle.jpg",
  },
  {
    id: "vision-craft",
    title: "VISION CRAFT",
    subtitle: "UI/UX Design",
    category: "creative",
    categoryIcon: "🎨",
    clubId: "design-matrix",
    teamSize: "1–2",
    duration: "3 Hours",
    venue: "Design Lab",
    date: "21 October 2026",
    time: "10:00 AM – 1:00 PM",
    fee: "Free Entry",
    description: "Design stunning interfaces and user experiences. From wireframes to high-fidelity prototypes — bring ideas to life visually.",
    rules: [
      "Individual or pairs",
      "Design tool: Figma (required)",
      "Theme revealed at start",
      "Must present a clickable prototype",
      "Judging: aesthetics, UX, innovation",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹15,000" },
      { position: "🥈 2nd Place", amount: "₹9,000" },
      { position: "🥉 3rd Place", amount: "₹5,000" },
    ],
    image: "/events/design.jpg",
  },
  {
    id: "reel-rush",
    title: "REEL RUSH",
    subtitle: "Reel Making",
    category: "creative",
    categoryIcon: "🎨",
    clubId: "cinema-reels",
    teamSize: "1–3",
    duration: "48 Hours",
    venue: "Online Submission",
    date: "19–21 October 2026",
    time: "Deadline: 21 Oct 6 PM",
    fee: "Free Entry",
    description: "Create a short-form reel that captures the spirit of NEXUS 2026. Storytelling meets cinematic vision in 60 seconds or less.",
    rules: [
      "Maximum duration: 60 seconds",
      "Must include event branding",
      "Original content only",
      "Submit via portal by deadline",
      "Judging: creativity, editing, storytelling",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹10,000" },
      { position: "🥈 2nd Place", amount: "₹6,000" },
      { position: "🥉 3rd Place", amount: "₹3,000" },
    ],
    image: "/events/reel.jpg",
  },
  {
    id: "shutter-strike",
    title: "SHUTTER STRIKE",
    subtitle: "Photography",
    category: "creative",
    categoryIcon: "🎨",
    clubId: "lens-shutter",
    teamSize: "1",
    duration: "All Day",
    venue: "Campus-wide",
    date: "21 October 2026",
    time: "9:00 AM – 5:00 PM",
    fee: "Free Entry",
    description: "Capture the essence of NEXUS through your lens. Theme-based photography competition across the campus.",
    rules: [
      "Individual participation only",
      "Phone or DSLR allowed",
      "Submit top 5 photos by 5 PM",
      "Basic editing allowed, no composites",
      "Theme announced at 9 AM",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹8,000" },
      { position: "🥈 2nd Place", amount: "₹5,000" },
      { position: "🥉 3rd Place", amount: "₹3,000" },
    ],
    image: "/events/photography.jpg",
  },
  {
    id: "quest-royale",
    title: "QUEST ROYALE",
    subtitle: "Gaming Tournament",
    category: "battle",
    categoryIcon: "⚔️",
    clubId: "esports-arena",
    teamSize: "1",
    duration: "4 Hours",
    venue: "Gaming Arena",
    date: "21 October 2026",
    time: "11:00 AM – 3:00 PM",
    fee: "Free Entry",
    description: "Solo battle royale gaming tournament. Last one standing wins. Prove your skills in the ultimate 1v1 arena.",
    rules: [
      "Solo participation",
      "Game: BGMI",
      "Multiple rounds",
      "Points system: kills + placement",
      "Must use own mobile device",
    ],
    prizes: [
      { position: "🥇 1st Place", amount: "₹15,000" },
      { position: "🥈 2nd Place", amount: "₹8,000" },
      { position: "🥉 3rd Place", amount: "₹5,000" },
    ],
    image: "/events/gaming.jpg",
  },
];

export const SCHEDULE = [
  { time: "08:00 AM", event: "Gates Open — Registration Desk Active", category: "general", venue: "Main Gate" },
  { time: "09:00 AM", event: "Opening Ceremony — The Summoning", category: "general", venue: "Main Auditorium" },
  { time: "09:00 AM", event: "PIXEL FORGE — 24h Hackathon Begins", category: "tech", venue: "Main Auditorium" },
  { time: "10:00 AM", event: "ARC REACTOR — Coding Challenge", category: "tech", venue: "Computer Lab 01" },
  { time: "10:00 AM", event: "WEB WARS — Web Development", category: "tech", venue: "Computer Lab 02" },
  { time: "10:00 AM", event: "MIND MATRIX — Technical Quiz", category: "intelligence", venue: "Lecture Hall 3" },
  { time: "10:00 AM", event: "VISION CRAFT — UI/UX Design", category: "creative", venue: "Design Lab" },
  { time: "11:00 AM", event: "CYBER CLASH — Esports Tournament", category: "battle", venue: "Gaming Arena" },
  { time: "11:00 AM", event: "QUEST ROYALE — Gaming Tournament", category: "battle", venue: "Gaming Arena" },
  { time: "12:30 PM", event: "Lunch Break — Refuel Station", category: "general", venue: "Food Court" },
  { time: "01:00 PM", event: "Keynote Speaker — Industry Titan", category: "general", venue: "Main Auditorium" },
  { time: "02:00 PM", event: "WAR OF WORDS — Debate Championship", category: "battle", venue: "Seminar Hall" },
  { time: "03:00 PM", event: "ENIGMA — Puzzle Challenge", category: "intelligence", venue: "Room 105" },
  { time: "04:30 PM", event: "Workshop — Future of AI", category: "tech", venue: "Seminar Hall 2" },
  { time: "05:00 PM", event: "Results & Prize Distribution", category: "general", venue: "Main Auditorium" },
  { time: "06:00 PM", event: "Closing Ceremony — The Victory", category: "general", venue: "Main Auditorium" },
];

export const SPEAKERS = [
  {
    name: "Dr. Arjun Mehta",
    designation: "Professor, IIT Delhi",
    role: "Chief Guest",
    bio: "Distinguished Professor of Computer Science at IIT Delhi with 20+ years of research in AI and distributed systems. Recipient of the National Technology Award.",
  },
  {
    name: "Priya Sharma",
    designation: "CTO, TechVault Inc.",
    role: "Keynote Speaker",
    bio: "Leading voice in India's startup ecosystem. Built TechVault from a 2-person team to a 500+ engineering powerhouse. Forbes 30 Under 30.",
  },
  {
    name: "Rahul Krishnan",
    designation: "Senior Engineer, Google DeepMind",
    role: "Workshop Lead",
    bio: "AI researcher specializing in large language models and reinforcement learning. Published 30+ papers in top-tier conferences.",
  },
  {
    name: "Ananya Desai",
    designation: "Design Director, Flipkart",
    role: "Judge — Creative",
    bio: "Award-winning designer who led the redesign of Flipkart's mobile experience. Passionate about making technology accessible through design.",
  },
  {
    name: "Vikram Patel",
    designation: "Founder, CodeForge Labs",
    role: "Judge — Tech",
    bio: "Serial entrepreneur and competitive programming champion. Built multiple developer tools used by over 1M developers worldwide.",
  },
  {
    name: "Dr. Meera Nair",
    designation: "Director, Vanguard IT",
    role: "Host",
    bio: "Visionary leader of Vanguard Institute of Technology. Driving innovation in education through industry-academia partnerships.",
  },
];

export const LEADERBOARD = [
  { rank: 1, team: "QUANTUM SURGE", score: 980, event: "ARC REACTOR" },
  { rank: 2, team: "CODE AVENGERS", score: 945, event: "ARC REACTOR" },
  { rank: 3, team: "BYTE FORCE", score: 912, event: "WEB WARS" },
  { rank: 4, team: "TECH TITANS", score: 890, event: "NEURAL NEXUS" },
  { rank: 5, team: "PIXEL PIONEERS", score: 875, event: "WEB WARS" },
  { rank: 6, team: "NEURAL KNIGHTS", score: 860, event: "NEURAL NEXUS" },
  { rank: 7, team: "CYBER WOLVES", score: 842, event: "CYBER CLASH" },
  { rank: 8, team: "DATA DYNAMOS", score: 831, event: "ARC REACTOR" },
];

export const SPONSORS = {
  title: [{ name: "TechVault", logo: "/sponsors/techvault.svg" }],
  poweredBy: [{ name: "CloudNova", logo: "/sponsors/cloudnova.svg" }],
  gold: [
    { name: "ByteStream", logo: "/sponsors/bytestream.svg" },
    { name: "NeuralWorks", logo: "/sponsors/neuralworks.svg" },
    { name: "CodeForge", logo: "/sponsors/codeforge.svg" },
  ],
  silver: [
    { name: "DataPulse", logo: "/sponsors/datapulse.svg" },
    { name: "WebSphere", logo: "/sponsors/websphere.svg" },
    { name: "AppGrid", logo: "/sponsors/appgrid.svg" },
    { name: "StackBridge", logo: "/sponsors/stackbridge.svg" },
  ],
  community: [
    { name: "DevCommunity", logo: "/sponsors/devcommunity.svg" },
    { name: "HackClub", logo: "/sponsors/hackclub.svg" },
    { name: "OpenSource India", logo: "/sponsors/osi.svg" },
  ],
};

export const FAQS = [
  {
    question: "Who can participate in NEXUS 2026?",
    answer: "Any college student with a valid college ID can participate. Some events may have specific eligibility criteria mentioned in their respective event pages.",
  },
  {
    question: "Can I participate in multiple events?",
    answer: "Yes, as long as the event timings don't overlap. Check the schedule page to plan your participation across events.",
  },
  {
    question: "How do I register?",
    answer: "Click 'Register Now' on any event page, fill in your details, select your event, add team members if required, complete payment, and you'll receive a confirmation with a QR pass.",
  },
  {
    question: "Is there a registration fee?",
    answer: "Registration fees vary by event, ranging from ₹50 to ₹500. Check individual event pages for exact pricing.",
  },
  {
    question: "Where will I receive my registration confirmation?",
    answer: "You'll receive confirmation via email and it will also appear in your student dashboard with a downloadable QR pass.",
  },
  {
    question: "What should I bring on event day?",
    answer: "Bring your college ID, registration QR pass (digital or printed), laptop/peripherals for tech events, and your enthusiasm!",
  },
  {
    question: "Is food provided?",
    answer: "Yes, lunch and refreshments are included for all registered participants. The food court will be active throughout the day.",
  },
  {
    question: "Can I get a refund if I can't attend?",
    answer: "Refund requests made 7+ days before the event receive a full refund. Requests within 3-7 days receive 50%. No refunds within 3 days of the event.",
  },
  {
    question: "How do I reach the venue?",
    answer: "Vanguard Institute of Technology is accessible via Metro (nearest station: Hauz Khas). Free shuttle service from the metro station on event day.",
  },
  {
    question: "Who do I contact for queries?",
    answer: "Email us at nexus2026@vanguardit.edu or reach out on our Instagram @nexus2026. Help desk will be active on event day near the main gate.",
  },
];

export const ANNOUNCEMENTS = [
  {
    id: "1",
    title: "MISSION UPDATE",
    description: "Early bird registration closes on October 10th. Register now to avail 20% discount on all events!",
    date: "03 Oct 2026",
    priority: "high" as const,
  },
  {
    id: "2",
    title: "NEW MISSION ADDED",
    description: "PIXEL FORGE — 24-hour Hackathon has been added to the Tech Heroes category. Registration now open!",
    date: "01 Oct 2026",
    priority: "medium" as const,
  },
  {
    id: "3",
    title: "VENUE UPDATE",
    description: "CYBER CLASH esports tournament has been moved to the new Gaming Arena (Block C, Ground Floor).",
    date: "30 Sep 2026",
    priority: "low" as const,
  },
];
